[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev] 
    command = "next dev"
    targetPort = 3000


[[edge_functions]]
function = "set-cookies"
path = "/test"